server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: qetuMBCZ
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
  swagger:
    enabled: true